language: objective-c
osx_image: xcode10.2
xcode_workspace: Splashr-X.xcworkspace
xcode_scheme: Splashr-X
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
before_install:
  - pod repo update 
  - pod install
after_success:
  - gem install jazzy
  - jazzy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  local-dir: docs/source
  on:
    branch: develop