language: objective-c
osx_image: xcode10.2
script: xcodebuild -workspace Splashr-x.xcworkspace -scheme Splashr-X -destination "name=iPhone X,OS=12.2" | xcpretty
before_install:
  - pod repo update 
  - pod install

